name: pytorch-bsf
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- python=3.14
- "pytorch>=2,<3"
- "lightning>=2,<3"
- "mlflow>=3,<4"
- "jsonschema>=4,<5"
- "pyyaml>=6,<7"
- "protobuf>=6,<7"
- pip
- pip:
  - "pl-crossvalidate>=0.1,<1"
  - -e .
