name: pytorch-bsf
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- python=3.14
- cudatoolkit
- pytorch
- lightning
- torchmetrics
- mlflow
- starlette<1.0.0  # hotfix for mlflow's starlette 1.0.0 issue
- jsonschema
- pyyaml
- pip
- pip:
  - pl-crossvalidate
  - -e .
