name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        conda info
    - name: Install dependencies
      run: |
        conda env update --file conda.yaml --name base
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest pytest-cov
        pytest
    - name: E2E test with conda
      run: |
        cat << EOS > data.tsv
        1 2
        4 3
        5 6
        EOS
        cat << EOS > label.tsv
        1
        2
        3
        EOS
        python -m torch_bsf --data=data.tsv --label=label.tsv --degree=3 --gpus=0

  build-mlflow:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        conda info
    - name: Install dependencies
      run: |
        conda install -c conda-forge mlflow
    - name: E2E test with MLflow
      run: |
        cat << EOS > data.tsv
        1 2
        4 3
        5 6
        EOS
        cat << EOS > label.tsv
        1
        2
        3
        EOS
        mlflow run https://github.com/rafcc/pytorch-bsf -P data=data.tsv -P label=label.tsv -P degree=3 -P gpus=0
